[package]
name = "skass/ustud"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
RoactRouter = "reselim/roact-router@1.0.3"
InstanceQuerier = "u-train/instancequerier@0.0.1"
StudioComponents = "u-train/studiocomponents@0.1.1"
Maid = "flamenco687/maid@3.2.2"