[package]
name = "skass/ustud"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
RoactRouter = "reselim/roact-router@1.0.3"